# Generated by Django 3.0.4 on 2020-07-18 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='request',
        #     name='guid',
        # ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='waiting', max_length=32, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Request'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='waiting', max_length=32, verbose_name='服务状态'),
        ),
    ]
