# Generated by Django 2.1.15 on 2020-07-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200718_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='guid',
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uid',
            field=models.CharField(blank=True, max_length=64, verbose_name='唯一标准编号'),
        ),
    ]
