# Generated by Django 3.0.4 on 2020-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200720_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.FilePathField(verbose_name='文件路径'),
        ),
    ]
