# Generated by Django 3.0.4 on 2020-07-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200720_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.FilePathField(path='D:\\uploads\\res', verbose_name='文件路径'),
        ),
    ]
