# Generated by Django 3.0.4 on 2020-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200720_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.FileField(upload_to='D:\\uploads\\res', verbose_name='文件路径'),
        ),
    ]
