# Generated by Django 3.0.4 on 2020-07-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200720_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.FileField(blank=True, upload_to='uploads/res/%Y/%m/%d/', verbose_name='文件路径'),
        ),
    ]
