# Generated by Django 2.1.15 on 2020-07-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200721_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='path',
            new_name='attachment',
        ),
    ]
