# Generated by Django 2.1.15 on 2020-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200721_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dev', '开发员'), ('admin', '开发员'), ('user', '客服员'), ('seller', '销售员')], max_length=8, verbose_name='权限组'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
