# Generated by Django 2.1.15 on 2020-07-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200723_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='lang',
            field=models.CharField(choices=[('ZH', '中文'), ('F', '洋文')], default='ZH', max_length=12, verbose_name='语种'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('waiting', '等待中'), ('progress', '进行中'), ('success', '已成功'), ('failed', '已失败')], default='waiting', max_length=32, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', '等待中'), ('progress', '进行中'), ('success', '已成功'), ('failed', '已失败')], default='waiting', max_length=32, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dev', '开发员'), ('admin', '管理员'), ('user', '客服员'), ('seller', '销售员')], max_length=8, verbose_name='权限组'),
        ),
    ]
