# Generated by Django 3.0.4 on 2020-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_resource_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='short',
            field=models.CharField(blank=True, max_length=6, verbose_name='短地址'),
        ),
    ]
