# Generated by Django 2.1.15 on 2020-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200731_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='授权地纬度'),
        ),
        migrations.AddField(
            model_name='organ',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='授权地经度'),
        ),
        migrations.AddField(
            model_name='organ',
            name='range',
            field=models.IntegerField(default=1000, verbose_name='授权范围(m)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dept',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wechat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=2550, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='唯一标准编号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=2550, verbose_name='任务标题'),
        ),
    ]
