# Generated by Django 2.1.15 on 2020-08-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200812_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='range',
            field=models.IntegerField(blank=True, default=1000, verbose_name='授权范围(m)'),
        ),
    ]
