# Generated by Django 2.1.15 on 2020-09-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200831_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0, verbose_name='授权地纬度')),
                ('longitude', models.FloatField(default=0, verbose_name='授权地经度')),
                ('range', models.IntegerField(default=1000, verbose_name='授权范围(m)')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organ')),
            ],
        ),
    ]
