# Generated by Django 3.1.1 on 2020-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='expiry',
            field=models.IntegerField(default=7, verbose_name='授权有效期(天)'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='授权地纬度'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='授权地经度'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='range',
            field=models.IntegerField(default=1000, verbose_name='授权范围(m)'),
        ),
    ]
