# Generated by Django 3.0 on 2021-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200925_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='download',
            field=models.URLField(blank=True, max_length=1000, verbose_name='第三方下载地址'),
        ),
    ]
