# Generated by Django 2.1.15 on 2021-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.IntegerField(default=1, verbose_name='资源量'),
        ),
    ]
