# Generated by Django 2.1.15 on 2020-08-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0014_auto_20200812_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_auth', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('latitude', models.FloatField(blank=True, default=0, verbose_name='授权地纬度')),
                ('longitude', models.FloatField(blank=True, default=0, verbose_name='授权地经度')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
    ]
