# Generated by Django 2.1.15 on 2020-08-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='openid',
            field=models.CharField(blank=True, max_length=28, verbose_name='微信用户ID'),
        ),
    ]
