# Generated by Django 3.0.4 on 2020-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auth_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=28, verbose_name='微信用户ID')),
                ('latitude', models.FloatField(blank=True, default=0, verbose_name='授权地纬度')),
                ('longitude', models.FloatField(blank=True, default=0, verbose_name='授权地经度')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
            ],
        ),
    ]
