# Generated by Django 3.0.4 on 2020-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_auto_20200913_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
