# Generated by Django 3.0.4 on 2020-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0005_auth_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='status',
        ),
        migrations.AddField(
            model_name='auth',
            name='free',
            field=models.IntegerField(default=5, verbose_name='免费篇数'),
        ),
        migrations.AddField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='auth',
            name='level',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
    ]
