# Generated by Django 3.0 on 2020-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('total', models.PositiveIntegerField(verbose_name='日活次数')),
            ],
        ),
        migrations.CreateModel(
            name='D1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='今日服务量')),
                ('today', models.PositiveIntegerField(verbose_name='今日量')),
                ('yesterday', models.PositiveIntegerField(verbose_name='昨日量')),
                ('week', models.PositiveIntegerField(verbose_name='上周同期量')),
                ('max', models.PositiveIntegerField(verbose_name='月最高量')),
                ('days', models.PositiveIntegerField(verbose_name='服务天数')),
            ],
        ),
        migrations.CreateModel(
            name='D2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('hour', models.PositiveSmallIntegerField(verbose_name='小时')),
                ('total', models.PositiveIntegerField(verbose_name='总计')),
            ],
        ),
        migrations.CreateModel(
            name='D3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('total', models.PositiveIntegerField(verbose_name='总计')),
            ],
        ),
        migrations.CreateModel(
            name='D4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='今日服务量')),
                ('today', models.PositiveIntegerField(verbose_name='今日量')),
                ('yesterday', models.PositiveIntegerField(verbose_name='昨日量')),
                ('week', models.PositiveIntegerField(verbose_name='上周同期量')),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='部门名称')),
                ('value', models.PositiveIntegerField(verbose_name='需求量')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='群名称')),
                ('total', models.PositiveIntegerField(verbose_name='需求量')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZH', models.PositiveIntegerField()),
                ('F', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='机构名称')),
                ('total', models.PositiveIntegerField(verbose_name='需求量')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='显示名')),
                ('dept', models.CharField(max_length=32, verbose_name='部门')),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_type', models.CharField(max_length=32, verbose_name='资源名')),
                ('total', models.PositiveIntegerField(verbose_name='总计')),
            ],
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.FloatField()),
                ('failed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('total', models.PositiveIntegerField(verbose_name='需求')),
                ('success', models.PositiveIntegerField(verbose_name='回复')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('sales', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='客服')),
                ('total', models.PositiveIntegerField(verbose_name='总计')),
            ],
        ),
    ]
