# Generated by Django 3.1.6 on 2021-02-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('wxid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='群用户名')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('wxid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='群名')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('custom', '客户'), ('AI', 'AI'), ('CS', '客服')], default='custom', max_length=8)),
                ('date', models.DateTimeField(verbose_name='时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('state', models.IntegerField(choices=[(0, '未处理'), (1, '已处理'), (2, '转人工')], default=0)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.buddy')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.chatroom')),
            ],
        ),
        migrations.AddField(
            model_name='buddy',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.chatroom'),
        ),
    ]
