# Generated by Django 3.1.6 on 2021-02-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='name',
            field=models.CharField(max_length=128, verbose_name='群昵称'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
