# Generated by Django 3.0 on 2021-03-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_organ_code'),
        ('robot', '0002_auto_20210209_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='是否接单'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Request'),
        ),
    ]
