# Generated by Django 3.0 on 2020-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libgen_non_fiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.TextField(null=True)),
                ('Title', models.TextField(null=True)),
                ('Authors', models.TextField(null=True)),
                ('Year', models.CharField(max_length=4, null=True)),
                ('Publisher', models.TextField(null=True)),
                ('Libgenid', models.CharField(max_length=10, null=True)),
                ('FileId', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='libgen_scimag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doi', models.TextField(null=True)),
                ('Title', models.TextField(null=True)),
                ('Authors', models.TextField(null=True)),
                ('Year', models.CharField(max_length=4, null=True)),
                ('Journal', models.TextField(null=True)),
                ('PubmedId', models.TextField(null=True)),
                ('Libgenid', models.CharField(max_length=10, null=True)),
                ('FileId', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
